### ISSUE TITLE
播放某些MP4的视频 报错

### ISSUE THREAD

**Issue by MIkeeJY** [dueeeke/dkplayer#15]
com.danikula.videocache.ProxyCacheException: Error opening connection for http://v11-dy.ixigua.com/d7b74eb4aeef00f0c742d88e91af1e0a/5ad44b79/video/m/2205a1f000b42334a25a55c3c53b07ba066115402240000cbe323002791/ with offset 496000. Version: 2.7.0
                                                                at com.danikula.videocache.HttpUrlSource.open(HttpUrlSource.java:75)
                                                                at com.danikula.videocache.ProxyCache.readSource(ProxyCache.java:123)
                                                                at com.danikula.videocache.ProxyCache.access$100(ProxyCache.java:19)
                                                                at com.danikula.videocache.ProxyCache$SourceReaderRunnable.run(ProxyCache.java:187)
                                                                at java.lang.Thread.run(Thread.java:762)
                                                             Caused by: java.io.FileNotFoundException: http://v11-dy.ixigua.com/d7b74eb4aeef00f0c742d88e91af1e0a/5ad44b79/video/m/2205a1f000b42334a25a55c3c53b07ba066115402240000cbe323002791/
                                                                at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:254)
                                                                at com.danikula.videocache.HttpUrlSource.open(HttpUrlSource.java:70)
                                                                at com.danikula.videocache.ProxyCache.readSource(ProxyCache.java:123) 
                                                                at com.danikula.videocache.ProxyCache.access$100(ProxyCache.java:19) 
                                                                at com.danikula.videocache.ProxyCache$SourceReaderRunnable.run(ProxyCache.java:187) 
                                                                at java.lang.Thread.run(Thread.java:762)

**Comment by dueeeke** [comment]
@MIkeeJY 建议关闭缓存
