### ISSUE TITLE
视频缓存问题

### ISSUE THREAD

**Issue by chat491231702** [dueeeke/dkplayer#22]
`04-20 18:44:41.508 10141-10141/com.mvpow.tingjian E/DKPlayer: STATE_PREPARING
04-20 18:44:41.509 10141-10141/com.mvpow.tingjian E/DKPlayer: PLAYER_NORMAL
04-20 18:44:43.685 10141-10184/com.mvpow.tingjian W/OkHttpClient: A connection to http://127.0.0.1:33090/ was leaked. Did you forget to close a response body?
04-20 18:44:43.685 10141-10184/com.mvpow.tingjian I/chatty: uid=10245(u0_a245) OkHttp Connecti identical 2 lines
04-20 18:44:43.685 10141-10184/com.mvpow.tingjian W/OkHttpClient: A connection to http://127.0.0.1:33090/ was leaked. Did you forget to close a response body?
04-20 18:44:43.689 10141-10586/com.mvpow.tingjian E/HttpProxyCacheServer: HttpProxyCacheServer error
    com.danikula.videocache.ProxyCacheException: Error closing socket input stream. Version: 2.7.0
        at com.danikula.videocache.HttpProxyCacheServer.closeSocketInput(HttpProxyCacheServer.java:285)
        at com.danikula.videocache.HttpProxyCacheServer.releaseSocket(HttpProxyCacheServer.java:270)
        at com.danikula.videocache.HttpProxyCacheServer.processSocket(HttpProxyCacheServer.java:243)
        at com.danikula.videocache.HttpProxyCacheServer.access$200(HttpProxyCacheServer.java:52)
        at com.danikula.videocache.HttpProxyCacheServer$SocketProcessorRunnable.run(HttpProxyCacheServer.java:338)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:457)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: java.io.IOException: shutdown failed: ENOTCONN (Transport endpoint is not connected)
        at java.net.PlainSocketImpl.socketShutdown(PlainSocketImpl.java:267)
        at java.net.AbstractPlainSocketImpl.shutdownInput(AbstractPlainSocketImpl.java:582)
        at java.net.Socket.shutdownInput(Socket.java:1565)
        at com.danikula.videocache.HttpProxyCacheServer.closeSocketInput(HttpProxyCacheServer.java:278)
        at com.danikula.videocache.HttpProxyCacheServer.releaseSocket(HttpProxyCacheServer.java:270) 
        at com.danikula.videocache.HttpProxyCacheServer.processSocket(HttpProxyCacheServer.java:243) 
        at com.danikula.videocache.HttpProxyCacheServer.access$200(HttpProxyCacheServer.java:52) 
        at com.danikula.videocache.HttpProxyCacheServer$SocketProcessorRunnable.run(HttpProxyCacheServer.java:338) 
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:457) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636) 
        at java.lang.Thread.run(Thread.java:764) 
     Caused by: android.system.ErrnoException: shutdown failed: ENOTCONN (Transport endpoint is not connected)
        at libcore.io.Linux.shutdown(Native Method)
        at libcore.io.ForwardingOs.shutdown(ForwardingOs.java:176)
        at java.net.PlainSocketImpl.socketShutdown(PlainSocketImpl.java:265)
        at java.net.AbstractPlainSocketImpl.shutdownInput(AbstractPlainSocketImpl.java:582) 
        at java.net.Socket.shutdownInput(Socket.java:1565) 
        at com.danikula.videocache.HttpProxyCacheServer.closeSocketInput(HttpProxyCacheServer.java:278) 
        at com.danikula.videocache.HttpProxyCacheServer.releaseSocket(HttpProxyCacheServer.java:270) 
        at com.danikula.videocache.HttpProxyCacheServer.processSocket(HttpProxyCacheServer.java:243) 
        at com.danikula.videocache.HttpProxyCacheServer.access$200(HttpProxyCacheServer.java:52) 
        at com.danikula.videocache.HttpProxyCacheServer$SocketProcessorRunnable.run(HttpProxyCacheServer.java:338) 
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:457) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636) 
        at java.lang.Thread.run(Thread.java:764) 
04-20 18:44:43.689 10141-10649/com.mvpow.tingjian E/HttpProxyCacheServer: HttpProxyCacheServer error
    com.danikula.videocache.ProxyCacheException: Error closing socket input stream. Version: 2.7.0
        at com.danikula.videocache.HttpProxyCacheServer.closeSocketInput(HttpProxyCacheServer.java:285)
        at com.danikula.videocache.HttpProxyCacheServer.releaseSocket(HttpProxyCacheServer.java:270)
        at com.danikula.videocache.HttpProxyCacheServer.processSocket(HttpProxyCacheServer.java:243)
        at com.danikula.videocache.HttpProxyCacheServer.access$200(HttpProxyCacheServer.java:52)
        at com.danikula.videocache.HttpProxyCacheServer$SocketProcessorRunnable.run(HttpProxyCacheServer.java:338)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:457)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: java.io.IOException: shutdown failed: ENOTCONN (Transport endpoint is not connected)
        at java.net.PlainSocketImpl.socketShutdown(PlainSocketImpl.java:267)
        at java.net.AbstractPlainSocketImpl.shutdownInput(AbstractPlainSocketImpl.java:582)
        at java.net.Socket.shutdownInput(Socket.java:1565)
        at com.danikula.videocache.HttpProxyCacheServer.closeSocketInput(HttpProxyCacheServer.java:278)
        at com.danikula.videocache.HttpProxyCacheServer.releaseSocket(HttpProxyCacheServer.java:270) 
        at com.danikula.videocache.HttpProxyCacheServer.processSocket(HttpProxyCacheServer.java:243) 
        at com.danikula.videocache.HttpProxyCacheServer.access$200(HttpProxyCacheServer.java:52) 
        at com.danikula.videocache.HttpProxyCacheServer$SocketProcessorRunnable.run(HttpProxyCacheServer.java:338) 
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:457) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636) 
        at java.lang.Thread.run(Thread.java:764) 
     Caused by: android.system.ErrnoException: shutdown failed: ENOTCONN (Transport endpoint is not connected)
        at libcore.io.Linux.shutdown(Native Method)
        at libcore.io.ForwardingOs.shutdown(ForwardingOs.java:176)
        at java.net.PlainSocketImpl.socketShutdown(PlainSocketImpl.java:265)
        at java.net.AbstractPlainSocketImpl.shutdownInput(AbstractPlainSocketImpl.java:582) 
        at java.net.Socket.shutdownInput(Socket.java:1565) 
        at com.danikula.videocache.HttpProxyCacheServer.closeSocketInput(HttpProxyCacheServer.java:278) 
        at com.danikula.videocache.HttpProxyCacheServer.releaseSocket(HttpProxyCacheServer.java:270) 
        at com.danikula.videocache.HttpProxyCacheServer.processSocket(HttpProxyCacheServer.java:243) 
        at com.danikula.videocache.HttpProxyCacheServer.access$200(HttpProxyCacheServer.java:52) 
        at com.danikula.videocache.HttpProxyCacheServer$SocketProcessorRunnable.run(HttpProxyCacheServer.java:338) 
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:457) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636) 
        at java.lang.Thread.run(Thread.java:764) 
04-20 18:44:43.690 10141-10649/com.mvpow.tingjian W/HttpProxyCacheServer: Failed to close socket on proxy side: shutdown failed: ENOTCONN (Transport endpoint is not connected). It seems client have already closed connection.
04-20 18:44:43.690 10141-10586/com.mvpow.tingjian W/HttpProxyCacheServer: Failed to close socket on proxy side: shutdown failed: ENOTCONN (Transport endpoint is not connected). It seems client have already closed connection.
04-20 18:44:43.910 10141-10141/com.mvpow.tingjian E/DKPlayer: STATE_PREPARED`

**Comment by chat491231702** [comment]
04-29 21:41:50.884 2930-4238/com.mvpow.tingjian W/HttpProxyCacheServer: Failed to close socket on proxy side: shutdown failed: ENOTCONN (Transport endpoint is not connected). It seems client have already closed connection.
04-29 21:41:50.886 2930-2977/com.mvpow.tingjian E/HttpProxyCacheServer: HttpProxyCacheServer error
    com.danikula.videocache.ProxyCacheException: Error closing socket input stream. Version: 2.7.0
        at com.danikula.videocache.HttpProxyCacheServer.closeSocketInput(HttpProxyCacheServer.java:285)
        at com.danikula.videocache.HttpProxyCacheServer.releaseSocket(HttpProxyCacheServer.java:270)
        at com.danikula.videocache.HttpProxyCacheServer.processSocket(HttpProxyCacheServer.java:243)
        at com.danikula.videocache.HttpProxyCacheServer.access$200(HttpProxyCacheServer.java:52)
        at com.danikula.videocache.HttpProxyCacheServer$SocketProcessorRunnable.run(HttpProxyCacheServer.java:338)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:457)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: java.io.IOException: shutdown failed: ENOTCONN (Transport endpoint is not connected)
        at java.net.PlainSocketImpl.socketShutdown(PlainSocketImpl.java:267)
        at java.net.AbstractPlainSocketImpl.shutdownInput(AbstractPlainSocketImpl.java:582)
        at java.net.Socket.shutdownInput(Socket.java:1565)
        at com.danikula.videocache.HttpProxyCacheServer.closeSocketInput(HttpProxyCacheServer.java:278)
        at com.danikula.videocache.HttpProxyCacheServer.releaseSocket(HttpProxyCacheServer.java:270) 
        at com.danikula.videocache.HttpProxyCacheServer.processSocket(HttpProxyCacheServer.java:243) 
        at com.danikula.videocache.HttpProxyCacheServer.access$200(HttpProxyCacheServer.java:52) 
        at com.danikula.videocache.HttpProxyCacheServer$SocketProcessorRunnable.run(HttpProxyCacheServer.java:338) 
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:457) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636) 
        at java.lang.Thread.run(Thread.java:764) 
     Caused by: android.system.ErrnoException: shutdown failed: ENOTCONN (Transport endpoint is not connected)
        at libcore.io.Linux.shutdown(Native Method)
        at libcore.io.ForwardingOs.shutdown(ForwardingOs.java:176)
        at java.net.PlainSocketImpl.socketShutdown(PlainSocketImpl.java:265)
        at java.net.AbstractPlainSocketImpl.shutdownInput(AbstractPlainSocketImpl.java:582) 
        at java.net.Socket.shutdownInput(Socket.java:1565) 
        at com.danikula.videocache.HttpProxyCacheServer.closeSocketInput(HttpProxyCacheServer.java:278) 
        at com.danikula.videocache.HttpProxyCacheServer.releaseSocket(HttpProxyCacheServer.java:270) 
        at com.danikula.videocache.HttpProxyCacheServer.processSocket(HttpProxyCacheServer.java:243) 
        at com.danikula.videocache.HttpProxyCacheServer.access$200(HttpProxyCacheServer.java:52) 
        at com.danikula.videocache.HttpProxyCacheServer$SocketProcessorRunnable.run(HttpProxyCacheServer.java:338) 
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:457) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636) 
        at java.lang.Thread.run(Thread.java:764)

**Comment by dueeeke** [comment]
这是在什么情况下出现的

**Comment by chat491231702** [comment]
播放https协议的mp4，虽然不影响播放，但是console会有上面这些异常信息

**Comment by dueeeke** [comment]
不用管，这只是在关闭socket的时候抛出的异常，AndroidVideoCache的作者把这个异常封装了一下并且打印出来了，并不是什么问题

**Comment by chat491231702** [comment]
ok
