### ISSUE TITLE
播放问题：开启StrictMode时，切换地址会崩溃

### ISSUE THREAD

**Issue by DancingSnowInFingertips** [dueeeke/dkplayer#267]
问题如标题
错误log：
 E/StrictMode: A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.
    java.lang.Throwable: Explicit termination method 'release' not called
        at dalvik.system.CloseGuard.open(CloseGuard.java:223)
        at android.view.Surface.setNativeObjectLocked(Surface.java:557)
        at android.view.Surface.<init>(Surface.java:190)
        at com.sharker.video.player.IjkVideoView$2.onSurfaceTextureAvailable(IjkVideoView.java:148)
        at android.view.TextureView.getHardwareLayer(TextureView.java:390)
        at android.view.TextureView.draw(TextureView.java:339)
        at android.view.View.updateDisplayListIfDirty(View.java:18176)
        at android.view.View.draw(View.java:18954)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4240)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4024)
        at android.view.View.draw(View.java:19229)
        at android.view.View.updateDisplayListIfDirty(View.java:18176)
        at android.view.View.draw(View.java:18954)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4240)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4024)
        at android.view.View.updateDisplayListIfDirty(View.java:18167)
        at android.view.View.draw(View.java:18954)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4240)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4024)
        at android.view.View.updateDisplayListIfDirty(View.java:18167)
        at android.view.View.draw(View.java:18954)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4240)
        at com.google.android.material.appbar.CollapsingToolbarLayout.drawChild(CollapsingToolbarLayout.java:336)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4024)
        at android.view.View.draw(View.java:19229)
        at com.google.android.material.appbar.CollapsingToolbarLayout.draw(CollapsingToolbarLayout.java:299)
        at android.view.View.updateDisplayListIfDirty(View.java:18176)
        at android.view.View.draw(View.java:18954)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4240)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4024)
        at android.view.View.updateDisplayListIfDirty(View.java:18167)
        at android.view.View.draw(View.java:18954)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4240)
        at androidx.coordinatorlayout.widget.CoordinatorLayout.drawChild(CoordinatorLayout.java:1246)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4024)
        at android.view.View.updateDisplayListIfDirty(View.java:18167)
        at android.view.View.draw(View.java:18954)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4240)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4024)
        at android.view.View.updateDisplayListIfDirty(View.java:18167)
        at android.view.View.draw(View.java:18954)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4240)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4024)
        at android.view.View.updateDisplayListIfDirty(View.java:18167)
        at android.view.View.draw(View.java:18954)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4240)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4024)
        at android.view.View.updateDisplayListIfDirty(View.java:18167)
        at android.view.View.draw(View.java:18954)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4240)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4024)
        at android.view.View.updateDisplayListIfDirty(View.java:18167)
        at android.view.View.draw(View.java:18954)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4240)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4024)
        at android.view.View.draw(View.java:19229)
        at com.android.internal.policy.DecorView.draw(DecorView.java:791)
        at android.view.View.updateDisplayListIfDirty(View.java:18176)
        at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:685)
        at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:691)
        at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:799)
        at android.view.ViewRootImpl.draw(ViewRootImpl.java:3056)
        at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2851)
2019-06-22 23:39:11.597 10427-10449/? E/StrictMode:     at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2404)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1437)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6886)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1029)
        at android.view.Choreographer.doCallbacks(Choreographer.java:841)
        at android.view.Choreographer.doFrame(Choreographer.java:772)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1015)
        at android.os.Handler.handleCallback(Handler.java:794)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:176)
        at android.app.ActivityThread.main(ActivityThread.java:6651)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:824)

**Comment by DancingSnowInFingertips** [comment]
感谢作者开源，点个star表示敬意

**Comment by DancingSnowInFingertips** [comment]
我对本库的使用是复制到项目中对ui更改，使用方法如下：
 public void playVideo(AlbumInfo2.CatalogInfoBean.CourseListBean courseListBean) {
        viewSwitcher.setDisplayedChild(1);
        if (controller == null) {
            controller = new StandardVideoController(this);
        }
        controller.setTitle(courseListBean.getCourse_name());

        player.release();
        player.setUrl(courseListBean.getCourse_url());
        player.setVideoController(controller);
        player.start();

    }


关闭严格检查模式不会报错，打开会

**Comment by dueeeke** [comment]
3.0.2已修复

**Comment by DancingSnowInFingertips** [comment]
好的，Thanks
