### ISSUE TITLE
无wifi状态下，抖音效果直接崩溃，原因是空指针异常。。。。

### ISSUE THREAD

**Issue by kylin9749** [dueeeke/dkplayer#39]
学生党无意中找到了您的代码，作为安卓的新手来说真的非常好用，这里先给您说声谢谢，非常感谢您的分享，

其次我找到的bug是在无wifi的情况下，使用打开douyinActivity会直接崩溃，貌似是找不到提示正在使用移动网络的那个对象了

 java.lang.NullPointerException: Attempt to invoke virtual method 'void com.dueeeke.videoplayer.widget.StatusView.setMessage(java.lang.String)' on a null object reference
        at com.dueeeke.videoplayer.controller.BaseVideoController.showStatusView(BaseVideoController.java:102)
        at com.dueeeke.videoplayer.player.IjkVideoView.checkNetwork(IjkVideoView.java:194)
        at com.dueeeke.videoplayer.player.IjkVideoView.startPlay(IjkVideoView.java:117)
        at com.dueeeke.videoplayer.player.BaseIjkVideoView.start(BaseIjkVideoView.java:216)

**Comment by dueeeke** [comment]
修复了。https://github.com/dueeeke/dkplayer/blob/dev/app/src/main/java/com/dueeeke/dkplayer/widget/controller/DouYinController.java#L40
